# Site settings
title: Allen写字的地方 - 只有写下来才是自己的
author: Allen
email: 361541673@163.com
description: "编程不仅仅是代码的积累，也是思考深度和广度的积累，写博客是一种不错的途径"
#url: "http://roadtopro.me"
static_url: "http://jacoffee-blog.b0.upaiyun.com"

# Conversion
# excerpt_separator: "\n\n" control where Jekyll to extract the displaying part of post in the index page


# Build settings
markdown: redcarpet
lineanchors: true
extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

#Outputting
# permalink: none url will be like /:categories/:title.html category attribute is defined on the top of post
gems: [jekyll-paginate]
paginate: 66
paginate_path: "/archives/page:num/"


# Plugins
safe: false
# whitelist: []
# gems: [redcarpet_pygments]

#菜单配置
nav:
  - text: 首页
    url: /
    icon: icon-home
    class: home
  - text: 文章归档
    url: /archives/
    icon: icon-reorder
    class: none
  - text: 博客源代码
    url: https://github.com/jacoffee/jacoffee.github.io
    icon: icon-github
    class: none
  - text: Stackoverflow
    url: http://stackoverflow.com/users/1723227/allen-chou
    icon: icon-stack-overflow
    class: none  