# Site settings
title: Allen写字的地方
author: Allen
email: 361541673@163.com
description: "编程不仅仅是代码的积累，也是思考深度和广度的积累，写博客是一种不错的途径"
url: "http://roadtopro.me "

# Conversion
# excerpt_separator: "\n\n" control where Jekyll to extract the displaying part of post in the index page


# Build settings
markdown: redcarpet
lineanchors: true
extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

#Outputting
permalink: none # url will be like /:categories/:title.html  category attribute is defined on the top of post

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "default"


#菜单配置
nav:
  - text: 首页
    url: /
    icon: icon-home
    class: home
  - text: 文章归档
    url: /archives/
    icon: icon-reorder
    class: none
  - text: 关于我
    url: /contact/
    icon: icon-envelope-alt
    class: none
#  - text: 联系我
#    url: http://www.zhanxin.info/contact.html
#    icon: icon-heart
#    class: none
  - text: 博客源代码
    url: https://github.com/jacoffee/jacoffee.github.io
    icon: icon-github
    class: none

page:
  - text: 文章分类
    url: /archives/
    last: true
  - text: 友情链接
    url: /links.html
    last: true
  - text: 关于我
    url: /contact/
    last: false
